#!/bin/bash
# Configure DDEV to work with Coder's router
# This script generates .ddev/config.coder.yaml with proper hostname configuration
#
# Coder URL pattern: https://{app-slug}--{workspace}--{owner}--{id}.{domain}/
# DDEV needs: project_tld={domain} and name={app-slug}--{workspace}--{owner}--{id}

set -e

# Get project directory (current directory or first argument)
PROJECT_DIR="${1:-.}"
cd "$PROJECT_DIR"

# Ensure we're in a DDEV project
if [ ! -f .ddev/config.yaml ]; then
    echo "Error: Not a DDEV project directory (no .ddev/config.yaml found)"
    echo "Usage: $0 [project-directory]"
    echo ""
    echo "Run 'ddev config' first to initialize a DDEV project."
    exit 1
fi

# Extract Coder environment variables
WORKSPACE_NAME="${CODER_WORKSPACE_NAME:-}"
WORKSPACE_OWNER="${CODER_WORKSPACE_OWNER:-${CODER_OWNER:-}}"
WORKSPACE_ID="${CODER_WORKSPACE_ID:-}"

# Fallback: try to extract from hostname if env vars not available
if [ -z "$WORKSPACE_NAME" ] || [ -z "$WORKSPACE_ID" ]; then
    echo "Warning: Coder environment variables not fully available"
    echo "Attempting to extract from hostname..."
    # Container hostname format: coder-{workspace-id}
    WORKSPACE_ID=$(hostname | sed 's/coder-//')
fi

# Get Coder domain from CODER_AGENT_URL or prompt user
CODER_DOMAIN=""
if [ -n "${CODER_AGENT_URL:-}" ]; then
    # Extract domain from agent URL (e.g., https://coder.example.com/...)
    CODER_DOMAIN=$(echo "$CODER_AGENT_URL" | sed -E 's|https?://([^/]+).*|\1|')
    echo "Detected Coder domain from CODER_AGENT_URL: $CODER_DOMAIN"
elif [ -n "${CODER_URL:-}" ]; then
    # Extract domain from CODER_URL
    CODER_DOMAIN=$(echo "$CODER_URL" | sed -E 's|https?://([^/]+).*|\1|')
    echo "Detected Coder domain from CODER_URL: $CODER_DOMAIN"
else
    # Prompt user for Coder domain
    echo ""
    echo "Could not auto-detect Coder domain."
    echo "Please enter your Coder domain (e.g., pit-1.try.coder.app):"
    read -r CODER_DOMAIN
fi

# Validate we have all required information
if [ -z "$WORKSPACE_NAME" ] || [ -z "$WORKSPACE_OWNER" ] || [ -z "$WORKSPACE_ID" ] || [ -z "$CODER_DOMAIN" ]; then
    echo ""
    echo "Error: Missing required information:"
    echo "  Workspace Name:  ${WORKSPACE_NAME:-[missing]}"
    echo "  Workspace Owner: ${WORKSPACE_OWNER:-[missing]}"
    echo "  Workspace ID:    ${WORKSPACE_ID:-[missing]}"
    echo "  Coder Domain:    ${CODER_DOMAIN:-[missing]}"
    echo ""
    echo "Please ensure you're running inside a Coder workspace or set these manually:"
    echo "  export CODER_WORKSPACE_NAME=your-workspace"
    echo "  export CODER_WORKSPACE_OWNER=your-username"
    echo "  export CODER_WORKSPACE_ID=your-workspace-id"
    exit 1
fi

# Construct DDEV project name to match Coder's app URL pattern
# Pattern: {app-slug}--{workspace}--{owner}--{id}
# The app-slug is "ddev-web" as defined in template.tf
DDEV_PROJECT_NAME="ddev-web--${WORKSPACE_NAME}--${WORKSPACE_OWNER}--${WORKSPACE_ID}"

# Get the project TLD (Coder domain)
PROJECT_TLD="$CODER_DOMAIN"

echo ""
echo "=========================================="
echo "Configuring DDEV for Coder Router"
echo "=========================================="
echo "Project Directory: $PROJECT_DIR"
echo "DDEV Project Name: $DDEV_PROJECT_NAME"
echo "Project TLD:       $PROJECT_TLD"
echo "Expected URL:      https://${DDEV_PROJECT_NAME}.${PROJECT_TLD}/"
echo ""

# Create or update .ddev/config.coder.yaml
cat > .ddev/config.coder.yaml <<EOF
# DDEV configuration for Coder.com deployment
# Auto-generated by configure-ddev-router.sh
#
# This configures DDEV to work with Coder's router by setting:
# - project_tld: The Coder domain for proper URL routing
# - name: Matches Coder's app URL pattern (app-slug--workspace--owner--id)
#
# Coder URL pattern: https://{app-slug}--{workspace}--{owner}--{id}.{domain}/
# Where app-slug is "ddev-web" as defined in the Coder template

name: ${DDEV_PROJECT_NAME}
project_tld: ${PROJECT_TLD}

# Use router_http_port and router_https_port from global_config.yaml
# These should be 8080 and 8443 respectively for Coder port forwarding
EOF

echo "✓ Created .ddev/config.coder.yaml"
echo ""
echo "Configuration complete!"
echo ""
echo "Next steps:"
echo "  1. Start or restart DDEV: ddev restart"
echo "  2. Access your site at: https://${DDEV_PROJECT_NAME}.${PROJECT_TLD}/"
echo ""
echo "Note: The ddev-web app must be running in Coder's dashboard for the URL to work."
echo "      Check the 'Apps' section in your Coder workspace."